version: '3.8'

services:
  db:
    image: mysql
    restart: always
    container_name: mikushin-project-mysql
    env_file: ./.env
    environment:
      MYSQL_USERNAME: ${DB_USER?:err}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD?:err}
      MYSQL_DATABASE: ${DB_NAME?:err}
    ports:
      - ${DB_HOST?:err}:${DB_PORT?:err}:${DB_PORT?:err}
